# print("hello")
# print(45*3)
# print(3>2)
# print(3<2)
# a=[1,2,3,4]
# print(a)
# b=["사과","바나나","딸기"]
# print(b)
# print(a[2])
# print(b[1])
# print(a[-2])
# print(b[-3])
# print(a[1:4])
# print(a[0:2])
# print(b[0:2])
클래스=["태래","지우","해찬","시원","하민"]
print(클래스[1:4])
print(클래스[4])
print(클래스[0:3])
print(클래스[1])
print(클래스[2:])
print(클래스[:])
print(클래스[::-1])
print(클래스[::2])
print(클래스[::-2])
print(클래스[1::2])